defaults:
  - ql_cnn_overcooked

ALG_NAME: qfix-mono_cnn

QFIX:
  FIXER: qfix
  # FIXER: q+fix
  # FIXER: qfix-lin
  # FIXER: q+fix-lin

  FIXEE: vdn
  # FIXEE: qmix

  W_DELTA: 0.0
  W_GT: 0.0
  # DETACH_ADVANTAGES: True
