defaults:
  - vdn_ff_mpe

ALG_NAME: qfix-sum-alt_ff

QFIX:
  # FIXER: qfix
  # FIXER: q+fix
  FIXER: qfix-sum-alt
  # FIXER: q+fix-sum-alt

  # FIXEE: vdn
  # FIXEE: qmix

  W_DELTA: 0.0
  W_GT: 0.0
  # DETACH_ADVANTAGES: True
